# coding: utf-8

"""
    Orders v0

    Use the Orders Selling Partner API to programmatically retrieve order information. With this API, you can develop fast, flexible, and custom applications to manage order synchronization, perform order research, and create demand-based decision support tools.   _Note:_ For the JP, AU, and SG marketplaces, the Orders API supports orders from 2016 onward. For all other marketplaces, the Orders API supports orders for the last two years (orders older than this don't show up in the response).  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VerificationDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'prescription_detail': 'PrescriptionDetail'
    }

    attribute_map = {
        'prescription_detail': 'prescriptionDetail'
    }

    def __init__(self, prescription_detail=None):  # noqa: E501
        """VerificationDetails - a model defined in Swagger"""  # noqa: E501

        self._prescription_detail = None
        self.discriminator = None

        if prescription_detail is not None:
            self.prescription_detail = prescription_detail

    @property
    def prescription_detail(self):
        """Gets the prescription_detail of this VerificationDetails.  # noqa: E501

        Information regarding the prescription tied to the order.  # noqa: E501

        :return: The prescription_detail of this VerificationDetails.  # noqa: E501
        :rtype: PrescriptionDetail
        """
        return self._prescription_detail

    @prescription_detail.setter
    def prescription_detail(self, prescription_detail):
        """Sets the prescription_detail of this VerificationDetails.

        Information regarding the prescription tied to the order.  # noqa: E501

        :param prescription_detail: The prescription_detail of this VerificationDetails.  # noqa: E501
        :type: PrescriptionDetail
        """

        self._prescription_detail = prescription_detail

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VerificationDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VerificationDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
