# coding: utf-8

"""
    Report v2021-06-30

    The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.  # noqa: E501

    OpenAPI spec version: 2021-06-30
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.reports_api import ReportsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.reports_api.ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_report(self):
        """Test case for cancel_report

        cancelReport  # noqa: E501
        """
        pass

    def test_cancel_report_schedule(self):
        """Test case for cancel_report_schedule

        cancelReportSchedule  # noqa: E501
        """
        pass

    def test_create_report(self):
        """Test case for create_report

        createReport  # noqa: E501
        """
        pass

    def test_create_report_schedule(self):
        """Test case for create_report_schedule

        createReportSchedule  # noqa: E501
        """
        pass

    def test_get_report(self):
        """Test case for get_report

        getReport  # noqa: E501
        """
        pass

    def test_get_report_document(self):
        """Test case for get_report_document

        getReportDocument  # noqa: E501
        """
        pass

    def test_get_report_schedule(self):
        """Test case for get_report_schedule

        getReportSchedule  # noqa: E501
        """
        pass

    def test_get_report_schedules(self):
        """Test case for get_report_schedules

        getReportSchedules  # noqa: E501
        """
        pass

    def test_get_reports(self):
        """Test case for get_reports

        getReports  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()